spring.application.name=locadora-de-jogos

# H2 em memória
spring.datasource.url=jdbc:h2:mem:locadoradb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Garantir que os scripts data.sql sejam executados após o Hibernate criar o schema
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Se usar Spring Security e quiser liberar o frame do H2
spring.security.headers.frame=false
spring.jpa.defer-datasource-initialization=true

# ==============================
# SWAGGER
# ==============================
springdoc.swagger-ui.path=/swagger-ui.html

# ==============================
# JWT (Autenticação e Autorização)
# ==============================
jwt.secret=chave-super-secreta-turmas-1234567890
jwt.expiration-ms=3600000  



